### ISSUE TITLE
Features for CRAN submission

### ISSUE THREAD

**Issue by roboton** [agency-fund/rsurveycto#1]
Get to feature parity with python library leveraging official SurveyCTO API: https://pypi.org/project/pysurveycto/

Official API documentation [here](https://support.surveycto.com/hc/en-us/articles/360033156894-REST-API-documentation)

Also attached since that article is behind a login:
[REST API documentation – SurveyCTO Support Center.pdf](https://github.com/youth-impact/rscto/files/9264948/REST.API.documentation.SurveyCTO.Support.Center.pdf)
.

**Comment by jakejh** [comment]
@roboton I'd like to decide on a feature set for an initial CRAN release. Based on the existing API, I would suggest the following additions to the current functionality:

- [x] Download form attachments.
- [x] Support fetching encrypted forms and attachments.

Given we're already converting the json form data to a data.table, I think the direct download of form data in csv is unnecessary. I'd also suggest we leave the "write" capabilities in beta mode, and polish them in future versions. Thoughts?

**Comment by roboton** [comment]
Yeap I think if we get things in some kind of data frame we can leave it to other options to do the file type exports.

I very much trust your judgment here! Forge ahead and here for code review or anything else you need for support.

**Comment by jakejh** [comment]
Ok, see what you think of the latest version. Both the new features seem to be working well.

**Comment by roboton** [comment]
Is there a PR or branch diff I can have a look at?

**Comment by jakejh** [comment]
Unfortunately I neglected to make a separate branch 🤦 . There is this:

https://github.com/youth-impact/rsurveycto/compare/5b936b..3d9ebe

but I also separated the functions into separate files, so it's not terribly helpful.

Here is the main change to `scto_read()`:

https://github.com/youth-impact/rsurveycto/blob/3d9ebe7131d5c33c37fb3c2e81c88967b0059332/R/scto_read.R#L88-L91

The other change is the addition of `scto_get_attachments()`:

https://github.com/youth-impact/rsurveycto/blob/main/R/scto_get_attachments.R

**Comment by roboton** [comment]
LGTM - appreciate the documentation!
