### ISSUE TITLE
Consider merge with https://github.com/roboton/rsurveycto

### ISSUE THREAD

**Issue by roboton** [agency-fund/rsurveycto#2]

**Comment by jakejh** [comment]
@roboton Let me know if the most recent commit includes everything from your version.

**Comment by roboton** [comment]
looks good! have you done integration tests with third party services before? i was wondering if it would be worthwhile to have our own instance of surveycto to write some unit tests against?

**Comment by jakejh** [comment]
I was wondering a similar thing. An alternative might be to provide GitHub Actions with a [secret](https://docs.github.com/en/actions/security-guides/encrypted-secrets#accessing-your-secrets) containing surveycto credentials. Could we create a table and form on youth-impact's surveycto server that are used solely for testing?

**Comment by roboton** [comment]
Just added you to the surveycto instance where you can do whatever you
would like with the data there. If you fancy integration tests, this could
be the place to do it. I have some example data entered, along with some
cases. If you have questions about how SurveyCTO is organized/works feel
free to reach out!

Best, Rob

**Comment by roboton** [comment]
I was going to create my own paid instance and have it work off of that.
Don't want to muddle up their SurveyCTO instance too much. This way we have
full flexibility and no harm done if something screws up.
