### ISSUE TITLE
scto_catalog - Group Feature 

### ISSUE THREAD

**Issue by Louis-Alassane** [agency-fund/rsurveycto#20]
Hi, 

First thanks for the package it's awesome! 

I had a small feature suggestion. It would be awesome if scto_catalog() had an argument group (or returned a group column by default). 
That would be very useful to discriminate which pipeline the data should go into in automated workflows (for example we have three groups pre-field, ongoing, complete which have corresponding workflows). 

Obviously, you can already achieve this by combining scto_catalog() and scto_meta() but it would be a neat argument. 

Best, 
LA

**Comment by jakejh** [comment]
Hi @Louis-Alassane , please check out the latest version (0.1.6), in which the catalog data.table includes columns for group_id and group_title.

**Comment by Louis-Alassane** [comment]
Oh my bad, that's awesome!

**Comment by jakejh** [comment]
Not your bad, I just added the feature based on your request! ;-)

**Comment by jakejh** [comment]
Addressed in a657194.
